### ISSUE TITLE
cli-table is defunct, try cli-table3 (or better yet-- neo-blessed or blessed-contrib)

### ISSUE THREAD

**Issue by MarkSchmidty** [kurumiimari/shakedex#1]
[cli-table3](https://github.com/cli-table/cli-table3) is backwards compatible with the unmaintained cli-table. 
You can just swap it out and everything should work the same (but slightly better).

---- 

But, if you want to really impress people (AND make your work easier) check out:
### [@blessed/neo-blessed](https://www.npmjs.com/package/@blessed/neo-blessed). 
Blessed _can_ do a lot. But the basic building blocks are even easier than cli-table.
(There's even a **[blessed-cli](https://www.npmjs.com/package/@blessed/cli)** for designing the basic structure of a blessed app visually. It doesn't get much easier than that.)
![image](https://raw.githubusercontent.com/abritinthebay/nblessed/master/img/v0.1.0-3.gif)

### But wait, there's more-- [blessed-contrib](https://www.npmjs.com/package/@blessed/blessed-contrib) 
Blessed-Contrib adds:
- an easier to create and [simply better table implementation](https://github.com/yaronn/blessed-contrib#table)
- Easy handling of streaming data visualizations
- Lots more, and all surprisingly simple to work with
![image](https://github.com/yaronn/blessed-contrib/raw/master/docs/images/term3.gif)

### Don't be intimidated by how fancy these animations look
Building with [blessed-contrib](https://www.npmjs.com/package/@blessed/blessed-contrib) is **even easier than cli-table**, while also looking great.

Edit: It's also highly performant. Looks and works just as great on the lowest of low-end hardware.
Edit 2: (It's also MIT licensed.) If you don't try it out I will probably eventually get around to making a fork. But I encourage you to give it a try, because cli-table is a pain to work with.

**Comment by pinheadmz** [comment]
also: blessed was written by @chjj who is the lead developer of Handshake! ;-)

**Comment by kurumiimari** [comment]
Nice, thanks for the tip! Will take a look and swap the table implementation out later this week.

**Comment by kurumiimari** [comment]
Updated to `cli-table3` - I went this route because it was the fastest. I'll look at blessed more closely if we need a more involved terminal UI.
