### ISSUE TITLE
Reference hsd dependency by github link, not npm package

### ISSUE THREAD

**Issue by rithvikvibhu** [kurumiimari/shakedex#10]
With shakedex in Bob Wallet, the app (Bob wallet) fails to start because `names.json` is missing in `hsd`'s published package.

To use shakedex with Bob, it should reference the `hsd`'s GitHub repo directly, like how Bob Wallet does now: https://github.com/kyokan/bob-wallet/blob/master/package.json#L150

If the file doesn't exist, the app doesn't open:
```
Module not found: Error: Can't resolve './names.json' in '/media/data/Projects/handshake/bob-wallet/node_modules/shakedex/node_modules/hsd/lib/covenants'
```

**Comment by kurumiimari** [comment]
Ah, oh dear. Mind reporting this on the PR I opened on Bob Wallet? @chikeichan is putting the finishing touches on the PR and he should know about this.

**Comment by rithvikvibhu** [comment]
Contacted him first, then created this issue. Will mention it in the PR.
