### ISSUE TITLE
Cannot read property 'height' of null

### ISSUE THREAD

**Issue by pinheadmz** [kurumiimari/shakedex#3]
I think because you are calling `nodeClient.getTX()` here you should enforce in the docs that the local hsd full node must be run with `--index-tx`.

There might be other ways to do this, for example working with the hsd wallet maybe creating a new watch-only wallet that watches the p2sh address you create. Or instead of checking the TX, you could just check for the UTXO: https://hsd-dev.org/api-docs/#get-coin-by-outpoint

```
$ bin/shakedex list-auctions
An error occurred. Stack trace:
TypeError: Cannot read property 'height' of null
    at NameLockTransfer.getConfirmationDetails (/Users/matthewzipkin/Desktop/work/shakedex/src/nameLock.js:42:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async listAuctions (/Users/matthewzipkin/Desktop/work/shakedex/src/cli/main.js:283:23)
    at async Command.<anonymous> (/Users/matthewzipkin/Desktop/work/shakedex/src/cli/main.js:66:7)

Please report this as an issue by visiting https://github.com/kurumiimari/shakedex/issues/new.
```

**Comment by kurumiimari** [comment]
There are a bunch of sanity checks I need to do here, such as making sure that the HSD node is up and pre-verifying name ownership before trying to send transfer/finalize transactions. I'll update the docs to reflect `--index-tx` and add those sanity checks later this week.

**Comment by pinheadmz** [comment]
Cool but also you *could* skip that requirement if the code just looks up the `coin`.

i.e. replace this:

https://github.com/kurumiimari/shakedex/blob/8cf46ce11aa272f5663369216e19e0fe11e82805/src/nameLock.js#L40

with something more like what you have here:

https://github.com/kurumiimari/shakedex/blob/8cf46ce11aa272f5663369216e19e0fe11e82805/src/swapProof.js#L44-L47

The `getCoin()` [API](https://hsd-dev.org/api-docs/#get-coin-by-outpoint) will still give you the confirmation height.
