### ISSUE TITLE
Passphrase required

### ISSUE THREAD

**Issue by pinheadmz** [kurumiimari/shakedex#4]
I ran through both sides of the auction process locally on regtest, I was only asked for my wallet passphrase for two steps, `fulfill-auction` and `finalize-auction` (the two buyer-side actions).

1. The CLI wouldn't accept empty passphrase (I just entered ` ` (space) and it worked -- this is an unencrypted wallet)
2. Feels like the passphrase should have been required to create the auction TXs because they are signed, why wasn't this required?

**Comment by kurumiimari** [comment]
Good point - I will update the passphrase method to support empty passphrases if necessary.

Re: the passphrase - I'll look into this. The code should be asking for a passphrase wherever we create a keyring, which is required to create the auction TXs.

**Comment by pinheadmz** [comment]
Ohhhh I see, you are generating a new key pair just for the swap wallet and storing it in a local DB, I thought it was coming from the associated hsd wallet as well. Hmmm interesting. Since this is the case, you may want to emphasize to the user to backup the DB, or actually offer them a seed phrase to back up on wallet initialization. I guess since you are signing a funky script you probably can't use the usual wallet API so it makes sense that shakedex generates new keys.

**Comment by kurumiimari** [comment]
Yea, we have to use a special key to sign the script. I've added this to the docs.
